import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-pretendard"> {/* 전역에서 커스텀 폰트 사용 */}
        <Header />
        <div className="border-b-1 border-gray-100"></div>
        <div className="lg:mx-[128px] lg:my-[40px] 2xl:mx-[240px] 2xl:my-[70px]">
          {children}
        </div>
      </body>
    </html>
  );
}
